apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordeR-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: imperialx45/order_proc1:latest
        ports:
        - containerPort: 8000
